doc(references): Add references content model
livingdocsIO/documentation pull request #372
Opened 2021-03-11 21:03 UTC by ajwild

I'm not sure if this should be listed as a content model, or have its own section directly under "Reference Docs".

Examples taken from:
- https://github.com/livingdocsIO/livingdocs-server/pull/3341
- https://github.com/livingdocsIO/livingdocs-server/pull/3383

2021-03-12 08:16 UTC, DaRaFF approved these changes
I like how it is currently

2021-03-12 09:39 UTC, benib requested changes

2021-03-12 09:39 UTC, benib commented on reference-docs/content-model/references.md
> +References are stored for documents and media library entries. They indicate links from the document or entry to other content.
I'd love to see pointers to the Public API explaining how I can get to see these references.

2021-03-12 09:51 UTC, ajwild commented on reference-docs/content-model/references.md
> +References are stored for documents and media library entries. They indicate links from the document or entry to other content.
I didn't want to add too much info about the Public API into this content-model section, but a pointer is a good idea. Should I add a text description of how to find the public API docs and the section the references endpoints are in, or include a link to localhost?

2021-03-12 10:07 UTC, peyerluk commented on reference-docs/content-model/references.md
> +References are stored for documents and media library entries. They indicate links from the document or entry to other content.
We just link to edit.livingdocs.io when we refer to the API documentation.

2021-03-12 16:44 UTC, ajwild commented on reference-docs/content-model/references.md
> +References are stored for documents and media library entries. They indicate links from the document or entry to other content.
Done. Now that I think about it, I find it a bit strange that I've exposed the `references` property on 4 endpoints outside the Public API beta paths. I've deliberately not mentioned them in the docs here. We'll have to have a think about which endpoints should include references when we move from beta to v1, and either rethink how we select fields, or remove the references once they've been loaded from the database (not ideal).

For info, it's the copy, transform, and republish endpoints for documents, as they return the document without any transforms, and the more commonly used `/media-library/:mediaLibraryEntryId`. There's also the `/media-library?reference=image:FxZE7difmfvW` query which I should probably not have done, as it doesn't return any references :facepalm:

2021-03-14 16:26 UTC, benib approved these changes

2021-03-14 16:26 UTC, benib commented on reference-docs/content-model/references.md
> +References are stored for documents and media library entries. They indicate links from the document or entry to other content.
I don't fully understand this yet. But I guess you will act on it to come to a conclusion?

2021-04-06 12:51 UTC, merged

2021-04-07 00:23 UTC, livingdocs-automation commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/livingdocsIO/documentation/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: