Add doc for Media Type MediaFile
livingdocsIO/documentation pull request #395
Opened 2021-05-03 08:30 UTC by DaRaFF

2021-05-03 19:04 UTC, benib commented on content/enterprise/guides/media-library/index.md
> +Since `release-2021-06` you can manage your Files with the Livingdocs Media Library as well. It works pretty similar to the images. The solution still has some shortcomings you need to be aware of:
```suggestion
Since `release-2021-06` you can manage other files than videos and images with the Livingdocs Media Library as well. It works pretty similar to the images. The solution still has some shortcomings you need to be aware of:
```

2021-05-03 19:06 UTC, benib commented on content/enterprise/guides/media-library/index.md
> +- No render strategies or file services like you know them from images are available yet. That means the system works well if you render from the JSON in the delivery, but not so well if you let Livi
We currently add a link to the file to a paragraph. I guess the `services` in `file services` is referring to the image services, I would not mention that. I don't see why one would want to have anything like that for files.

2021-05-03 19:07 UTC, benib commented on content/enterprise/guides/media-library/index.md
> +- No render strategies or file services like you know them from images are available yet. That means the system works well if you render from the JSON in the delivery, but not so well if you let Livi
Also, it's not the same like with videos where you really want to do something with the directive data (therefore: render from JSON).
With files, this is not the case. Works perfectly fine with the `a` tags imo.

2021-05-03 19:07 UTC, benib commented on content/enterprise/guides/media-library/index.md
> +  handle: 'file', // you can name this as you like
There has to be one that is named `file` for now.

2021-05-03 19:08 UTC, benib commented on content/enterprise/reference-docs/project-config/media_types.md
>  - You can only configure 1 mediaType and it has to have the handle `image`.
Maybe something to fix, you can have multiple `mediaType`s, but one (the default) has to be named `image`.

2021-05-03 19:09 UTC, benib commented on content/enterprise/reference-docs/project-config/media_types.md
> +- Multiple Media Types of type `mediaImage` are supported, but at least one Media Type must have the handle `image`
You want to delete the line before imo

2021-05-03 19:10 UTC, benib requested changes
left some comments that should be considered imo

2021-05-05 05:27 UTC, DaRaFF commented on content/enterprise/reference-docs/project-config/media_types.md
>  - You can only configure 1 mediaType and it has to have the handle `image`.
I guess this was not possible for the July 2020 release.

2021-05-05 08:34 UTC, benib requested changes

2021-05-05 08:34 UTC, benib commented on content/enterprise/guides/media-library/index.md
> +  handle: 'image', // the handle is free, but one mediaImage must have the handle 'image'
```suggestion
  handle: 'image', // one mediaImage must have the handle 'image', additional ones can be named as you like
```

2021-05-05 08:34 UTC, benib commented on content/enterprise/guides/media-library/index.md
> +  handle: 'video', // the handle is free, but one mediaVideo must have the handle 'video'
```suggestion
  handle: 'video', // one mediaVideo must have the handle 'video', additional ones can be named as you like
```

2021-05-05 08:34 UTC, benib commented on content/enterprise/guides/media-library/index.md
> +  handle: 'file', // the handle is free, but one mediaFile must have the handle 'file'
```suggestion
  handle: 'file', // one mediaFile must have the handle 'file', additional ones can be named as you like
```

2021-05-05 08:34 UTC, benib commented on content/enterprise/reference-docs/project-config/media_types.md
>  - You can only configure 1 mediaType and it has to have the handle `image`.
But this line should be changed now right? It's not true anymore after all...

2021-05-05 08:34 UTC, benib commented on content/enterprise/reference-docs/project-config/media_types.md
> +  handle: 'file', // the handle is free, but one mediaFile must have the handle 'file'
```suggestion
  handle: 'file', // one mediaFile must have the handle 'file', additional ones can be named as you like
```

2021-05-05 08:34 UTC, benib commented on content/enterprise/reference-docs/project-config/media_types.md
> +  handle: 'video', // the handle is free, but one mediaVideo must have the handle 'video'
```suggestion
  handle: 'video', // one mediaVideo must have the handle 'video', additional ones can be named as you like
```

2021-05-05 10:12 UTC, DaRaFF commented on content/enterprise/reference-docs/project-config/media_types.md
>  - You can only configure 1 mediaType and it has to have the handle `image`.
But this is a log for people who are using release-2020-07. We can remove that sections in the future, but I would keep them for a while.

2021-05-05 10:15 UTC, benib approved these changes

2021-05-05 10:19 UTC, merged

2021-05-05 10:20 UTC, livingdocs-automation commented
:tada: This PR is included in version 1.3.5 :tada:

The release is available on [GitHub release](https://github.com/livingdocsIO/documentation/releases/tag/v1.3.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: