Extend oEmbed guide for new oEmbed providers (Instagram, Faceboook, Podigee)
livingdocsIO/documentation pull request #514
Opened 2022-06-28 15:08 UTC by gabrielhase

2022-06-28 15:19 UTC, ajwild commented on content/guides/documents/includes/oembed/index.md
> +    allowedCoreProviders: [{
This property needs moving up one level.

2022-06-28 15:21 UTC, ajwild commented on content/guides/documents/includes/oembed/index.md
> +- Facebook (`li-facebook-post`), ATTENTION: requires credentials
Can you use the added-in release thing here please.

2022-06-28 16:53 UTC, ajwild requested changes

2022-06-28 16:53 UTC, ajwild commented on content/guides/documents/includes/oembed/index.md
> +{{< added-in release-2022-07 >}}
It doesn't work there as it displays next to YouTube. You'll need to use it twice, once for Instagram and again for Facebook.

2022-06-28 18:25 UTC, gabrielhase commented on content/guides/documents/includes/oembed/index.md
> +{{< added-in release-2022-07 >}}
does this work? and how can you preview it?

2022-06-28 20:04 UTC, ajwild commented on content/guides/documents/includes/oembed/index.md
> +{{< added-in release-2022-07 >}}
I thought like this:
```js
- Instagram (`li-instagram`), ATTENTION: requires credentials {{< added-in release-2022-07 >}}
- Facebook (`li-facebook-post`), ATTENTION: requires credentials {{< added-in release-2022-07 >}}
```
or:
```js
- Instagram (`li-instagram`) {{< added-in release-2022-07 >}} ATTENTION: requires credentials
- Facebook (`li-facebook-post`) {{< added-in release-2022-07 >}} ATTENTION: requires credentials
```
Which ever looks better.

You can preview it with `npm run start` after installing [Hugo](https://gohugo.io/).

2022-06-30 14:21 UTC, ajwild approved these changes
You may as well backport Datawrapper and Spotify and add them to the list too before merging.

2022-06-30 18:33 UTC, merged

2022-06-30 18:35 UTC, livingdocs-automation commented
:tada: This PR is included in version 1.55.107 :tada:

The release is available on [GitHub release](https://github.com/livingdocsIO/documentation/releases/tag/v1.55.107)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: