fix(component prefilling): added to design v2
livingdocsIO/documentation pull request #551
Opened 2022-08-26 11:59 UTC by JSchenk8

Updated the component prefilling docs with example config and component property

2022-08-26 14:12 UTC, DaRaFF requested changes
Thanks for adding that! Please fix my feedback. We still can work a lot on making descriptions/configs more clear and I still try to find out the best way to do that.

2022-08-26 14:12 UTC, DaRaFF commented on content/reference-docs/document/document-design/_index.md
> +prefilledComponents: [{
I reviewed some document PRs recently with configs and I think it's much clearer if you show the whole Project Config object (you could fix that in the whole file).

<<<<
You can enable Prefilled Components by adding them to the Design Settings.

```js
{
  v: 2,
  ...
  designSettings: {
    prefilledComponents: [{
      component: 'title',
      content: [{
        directive: 'author',
        value: 'author', // can be 'author' or 'author-date'
        type: 'computed'
      }]
    }]
  }
}
```
<<<<

2022-08-26 14:12 UTC, DaRaFF commented on content/reference-docs/document/document-design/_index.md
> +Make sure you then have a directive in your component which can be prefilled, for example:
```suggestion
As a second step, you have to add a Design Component `title` which contains a directive `author`. After that when you add the `title` component to a document, the `author` should be prefilled automatically.
```

2022-08-29 07:28 UTC, JSchenk8 commented
@DaRaFF thanks very much for the thorough review, makes a lot of sense! I will take this into other documentation edits too, let me know how this version is now 🚀 🙏

2022-08-29 09:59 UTC, DaRaFF approved these changes
Yep, now it looks good, thx 👍

2022-08-29 10:00 UTC, merged

2022-08-29 10:02 UTC, livingdocs-automation commented
:tada: This PR is included in version 1.63.22 :tada:

The release is available on [GitHub release](https://github.com/livingdocsIO/documentation/releases/tag/v1.63.22)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: