Push messages docs
livingdocsIO/documentation pull request #584
Opened 2022-11-02 08:42 UTC by dfreier

2022-11-02 12:53 UTC, DaRaFF requested changes
Well done! 

I have some feedback you can consider for all documentation you write here:
- Always try to describe the use case for a guide or the feature -> what problem do I solve with that feature, why should I use that feature?
- The most important part of the documentation is the reference doc. As soon as a config has been added, it must be added to the reference doc. A guide is a nice addition. Guides and Reference doc should reference each other
- Try to link as much as possible, it helps readers to jump easily to the right places
- Concepts/Entities should always be written in big letters, e.g. Table Dashboard

2022-11-02 12:53 UTC, DaRaFF commented on content/guides/editor/push-messages/index.md
> +As an alternative to the existing [Push Notifications](https://docs.livingdocs.io/guides/editor/push-notifications) feature,
Do we already have a recommendation that people should switch to the new version? The past showed that we have too much alternatives and customers are confused.

2022-11-02 12:53 UTC, DaRaFF commented on content/guides/editor/push-messages/index.md
> +---
- I miss the explanation of what Push Notifications are 
- It would also be nice if we have cross-linked both Push Notification alternatives (in both directions)

2022-11-02 12:53 UTC, DaRaFF commented on content/guides/editor/push-messages/index.md
> +we developed the more flexible `li-push-messages` plugin. The two features may be merged in the future,
Add links wherever possible, e.g. here "plugin". I would rename that to "Metadata Plugin"

2022-11-02 12:53 UTC, DaRaFF commented on content/guides/editor/push-messages/index.md
> +1. Configure a metadata field on the content types that should support push messages
All concepts e.g. "Content Type" are written with capital letters. Also add a link to https://docs.livingdocs.io/reference-docs/project-config/content-types/

2022-11-02 12:53 UTC, DaRaFF commented on content/guides/editor/push-messages/index.md
> +title: Push Messages
The description of Push Messages is missing here -> https://docs.livingdocs.io/reference-docs/project-config/content-types/. A guide is always "only" an extension. But the Server Config and Project Config should always be complete.

2022-11-02 12:53 UTC, DaRaFF commented on content/guides/editor/push-messages/index.md
> +article.js
remove

2022-11-02 12:53 UTC, DaRaFF commented on content/guides/editor/push-messages/index.md
> +{
I would add a comment here
// Content Type

2022-11-02 12:53 UTC, DaRaFF commented on content/guides/editor/push-messages/index.md
> +    handlerName: 'myPushMessageHandler' // Optional, name of the registered function to send the message
Out of curiosity, what happens when there is no registered function and why is this optional?

2022-11-02 12:53 UTC, DaRaFF commented on content/guides/editor/push-messages/index.md
> +Check the [`li-push-messages` metadata plugin reference docs](https://docs.livingdocs.io/reference-docs/document/metadata/metadata-plugin-list/#li-push-messages) for further details.
If you have added already a link before, you don't need to write an extra sentence.

2022-11-02 12:53 UTC, DaRaFF commented on content/guides/editor/push-messages/index.md
> +Adding the push message button on a table dashboard is simple:
Table Dashboard (and a link to it)

2022-11-02 12:53 UTC, DaRaFF commented on content/guides/editor/push-messages/index.md
> +- Define another column on the table dashboard
Table Dashboard

2022-11-02 12:53 UTC, DaRaFF commented on content/guides/editor/push-messages/index.md
> +- See how to [configure a table dashboard](https://docs.livingdocs.io/reference-docs/project-config/editor-settings/#example-table-dashboard)
rm sentence

2022-11-02 12:53 UTC, DaRaFF commented on content/operations/releases/release-2022-11.md
> +As an alternative to the existing [Push Notifications](https://docs.livingdocs.io/guides/editor/push-notifications) feature,
thx 👍

2022-11-03 08:10 UTC, dfreier commented on content/guides/editor/push-messages/index.md
> +As an alternative to the existing [Push Notifications](https://docs.livingdocs.io/guides/editor/push-notifications) feature,
No not really. The reason why we have it is that SZ needs it that way (at least that's what I know). But there are discussions to merge the two features in another release.

2022-11-03 08:11 UTC, dfreier commented on content/guides/editor/push-messages/index.md
> +---
Sure, I can insert a link from the Push Notification to Push Messages as well.

2022-11-03 08:15 UTC, dfreier commented on content/guides/editor/push-messages/index.md
> +title: Push Messages
I can add a very short section in the Content Types doc with just two links to the guide and the plugin reference doc.

2022-11-03 08:19 UTC, dfreier commented on content/guides/editor/push-messages/index.md
> +    handlerName: 'myPushMessageHandler' // Optional, name of the registered function to send the message
The push message will be saved and the user sees a success message. Developers might choose another way how the messages are processed (e.g. by listening to document update events and then processing the messages from there).

2022-11-07 07:11 UTC, DaRaFF approved these changes
👍 nice, thanks for the changes

2022-11-07 07:12 UTC, merged

2022-11-07 08:01 UTC, livingdocs-automation commented
:tada: This PR is included in version 1.66.130 :tada:

The release is available on [GitHub release](https://github.com/livingdocsIO/documentation/releases/tag/v1.66.130)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: