A custom table dashboard cell example
livingdocsIO/documentation pull request #599
Opened 2022-12-13 14:31 UTC by JSchenk8

Here is a simple custom dashboard cell showing scheduled publish date

2022-12-14 05:37 UTC, DaRaFF commented on content/reference-docs/editor-extensions/vue-component-registry.md
> +An example dashboard cell here shows the time property for a scheduled publish document using the new [publish control]({{< ref "/guides/editor/publish-control/publish-control-basics.md" >}})
Move that guide to the guides and add a link here. The reference docs should not be too long and only explain the extension and its properties. But implementations should be shown via guides.

2022-12-15 07:22 UTC, JSchenk8 commented on content/reference-docs/editor-extensions/vue-component-registry.md
> +An example dashboard cell here shows the time property for a scheduled publish document using the new [publish control]({{< ref "/guides/editor/publish-control/publish-control-basics.md" >}})
Great, thanks! I've updated it, let me know what you think :)

2022-12-15 10:19 UTC, DaRaFF requested changes
I know documentation is really hard (btw, you did not do a bad job, but I guess we all need to get better, sorry that I'm using your PR as general criticism).

But see it like that:
Whenever you provide precise documentation, the whole team and customers save a lot of time.
I would say for guides these things are important:
- Motivation when and why you should use that approach and when another approach is better
- All helpful links to other sources (e.g. reference doc)
- Sometimes images to imagine the result (even when it can be outdated, but you get a general idea)

2022-12-15 10:19 UTC, DaRaFF commented on content/guides/editor/custom-table-dashboard-cells.md
> +With the table dashboard introduced in March 2022 we offer custom read-only cells.
`table dashboard` -> `Table Dashboard`. We decided to write all Livingdocs entities with a big character. 

The motivation for an extension guide should always contain an explanation of when and why one should write an extension. Our default is using the default features with configs, so there should be a good reason to not use that standard.

Long time ago I was writing something similar, maybe you can get some inspiration here -> https://docs.livingdocs.io/guides/search/custom-index/

2022-12-15 10:19 UTC, DaRaFF commented on content/guides/editor/custom-table-dashboard-cells.md
> +With the table dashboard introduced in March 2022 we offer custom read-only cells.
We should also always tell the advantages and disadvantages of an extension.

2022-12-15 10:19 UTC, DaRaFF commented on content/guides/editor/custom-table-dashboard-cells.md
> +Below is an example dashboard cell showing the time property for a scheduled publish document using the new [publish control]({{< ref "/guides/editor/publish-control/publish-control-basics.md" >}})
I still like screenshots where you can see the result (also with a red border to see which cell is custom)

2022-12-15 10:19 UTC, DaRaFF commented on content/guides/editor/custom-table-dashboard-cells.md
> +This must be registered in the vue component registry:
at the editor

2022-12-15 10:19 UTC, DaRaFF commented on content/guides/editor/custom-table-dashboard-cells.md
> +And can be configured for use in a table dashboard in the `editor_settings` in the server:
on the server in the Project Config (with a link to the editor settings in the reference docs)

2022-12-15 10:24 UTC, DaRaFF commented on content/guides/editor/custom-table-dashboard-cells.md
> +columns: [
// projectConfig.editorSettings

2022-12-23 12:28 UTC, JSchenk8 commented
@DaRaFF  Thank you for the thorough review, I really appreciate improving my documentation. I have followed your advice and hopefully clarified things. Let me know what you think, more feedback welcome

2023-01-11 10:41 UTC, DaRaFF approved these changes
Nice, please consider my comments and after that you can merge it.

2023-01-11 10:41 UTC, DaRaFF commented on content/guides/editor/custom-table-dashboard-cells.md
> +With the Table Dashboard introduced in March 2022 we have created upstream components configurable to suit most customer needs. We would highly recommend using these upstream components.
Why do we recommend upstream components?
My best guess is:
- less code
- less maintenance
- better integration with other features (indexing, dashboard filter, metadata plugins)

2023-01-11 10:41 UTC, DaRaFF commented on content/guides/editor/custom-table-dashboard-cells.md
> +However, we also offer custom read-only cells for times when you have small requirements to display in a Table Dashboard. For example, if you have a custom metadata field you want displayed.
> if you have a custom metadata field you want displayed

This is already possible. Maybe you should describe in more detail what you mean (e.g. a different presentation).

2023-05-05 14:15 UTC, merged

2023-05-05 14:17 UTC, livingdocs-automation commented
:tada: This PR is included in version 1.72.11 :tada:

The release is available on [GitHub release](https://github.com/livingdocsIO/documentation/releases/tag/v1.72.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: