WIP: li2xliff guide
livingdocsIO/documentation pull request #601
Opened 2022-12-15 08:55 UTC by JSchenk8

WIP

2022-12-23 12:42 UTC, JSchenk8 commented
@DaRaFF @looer @meinradandermatt  I struggled to find the balance between enough and too much detail here. Could happily add more, but hopefully it is clear enough for other developers to get started. Let me know what you think, very happy to revisit the depth.

2023-01-04 20:25 UTC, meinradandermatt requested changes

2023-01-04 20:25 UTC, meinradandermatt commented on content/guides/integrations/li2xliff/index.md
> +In your Livingdocs Server instance you can register a translation [access-hook]({{< ref "/guides/authentication/access-hooks.md" >}}) which can then send your document for translation:
why an access hook? We use the server events.

2023-01-05 10:30 UTC, JSchenk8 commented on content/guides/integrations/li2xliff/index.md
> +In your Livingdocs Server instance you can register a translation [access-hook]({{< ref "/guides/authentication/access-hooks.md" >}}) which can then send your document for translation:
I was confused about registering the hook which also listens to the server event. Would you say we could simplify this guide with just a link to the sever events docs? (here)[https://docs.livingdocs.io/reference-docs/server-extensions/server-events/]

2023-01-05 20:19 UTC, meinradandermatt commented on content/guides/integrations/li2xliff/index.md
> +In your Livingdocs Server instance you can register a translation [access-hook]({{< ref "/guides/authentication/access-hooks.md" >}}) which can then send your document for translation:
yes that make sense

2023-01-06 08:49 UTC, looer commented
I think you can add everything from the [Readme](https://github.com/livingdocsIO/li2xliff) to the guide as well.

Then would be cool to have an example of the full implementation, removing everything from NZZ and simplifying it a little, because customer are going to ask questions about how to have it fully working in the downstream.

2023-01-09 10:22 UTC, JSchenk8 commented
@meinradandermatt  I've updated the server subscription section. I added a link to the initialized hook docs after discussion with @looer . What do you think about adding a full implementation guide? Or is this enough?

2023-01-10 10:58 UTC, DaRaFF commented on content/reference-docs/project-config/settings.md
> +If you want to use a computer assisted translation (CAT) tool to translate livingdocs content you can install our li2xliff library to convert documents to XLIFF for translation and register server ho
add a link to
- "server hooks"
- "here" add guide link

2023-01-10 10:58 UTC, DaRaFF commented on content/guides/integrations/li2xliff/index.md
> +excludeEditables: [{
formatting looks not consistent

2023-01-10 10:58 UTC, DaRaFF commented on content/guides/integrations/li2xliff/index.md
> +  const xliffContent = createXliff({
formatting looks not consistent

2023-01-10 11:07 UTC, DaRaFF commented on content/guides/integrations/li2xliff/index.md
> +  const xliffContent = createXliff({
I think that's easier to read and to copy.

```js
const xliffContent = createXliff(
  {
    content: documentVersion.content, // Livingdocs Content
    config: {

      // required
      targetLanguage: config.targetLanguage,
      // required
      srcLanguage: config.srcLanguage,

      // optional
      excludeEditables: [
        {
          component: 'title',
          // this will not translate title or author editables inside title components
          editables: ['title', 'author']
        },
        {
          component: 'header',
          // this will not translate titles inside header components
          editables: ['title']
        }
      ],
      // optional - this will translate content inside of strong and anchor tags, but will not preserve the formatting
      excludeTags: ['strong', 'a']
    }
  }
)
```

2023-01-11 10:47 UTC, JSchenk8 commented on content/reference-docs/project-config/settings.md
> +If you want to use a computer assisted translation (CAT) tool to translate livingdocs content you can install our li2xliff library to convert documents to XLIFF for translation and register server ho
@DaRaFF Great thank you, I've added these and updated the format 🚀

2023-01-11 15:04 UTC, looer commented
Some suggestions:
- Add the instruction for installing using `npm install` like in the Readme
- Add link to the library on Github
- Add a mention of what is a CAT tool and some examples with links. Ex Phrase/Memsource, Smartcat, ...
- Update the title to be more homogenous with the other guides. from "Using li2xliff and CAT tools for translating Livingdocs content" to "Assisted translation with CAT tool", and keep the subtitle the same.
![image](https://user-images.githubusercontent.com/1682803/211839944-8e509089-965a-4b6c-9a4b-32db64889cc3.png)

2023-01-16 08:53 UTC, JSchenk8 commented
@looer Thanks very much! I changed it to reflect your advice, but I didn't recommend a CAT tool as I feel it's not up to us to guide them towards any particular tools, although we can of course say if they ask that "we have set it up with Memsource". Much appreciated 🙏

2023-01-16 10:00 UTC, DaRaFF approved these changes

2023-01-17 13:03 UTC, merged

2023-01-17 13:06 UTC, livingdocs-automation commented
:tada: This PR is included in version 1.68.153 :tada:

The release is available on [GitHub release](https://github.com/livingdocsIO/documentation/releases/tag/v1.68.153)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: