Update Documentation for Document Teasers
livingdocsIO/documentation pull request #834
Opened 2024-04-29 09:43 UTC by christian-schmitz-ld

# Motivation

NZZ wanted to test editable teasers, read the docs and reached out for help. I tried to setup an example configuration for them. Out of the given documentation I found it very difficult to understand the teaser guide. After digging deep and lots of testing I do now understand the implementation and therefore I want to fill gaps on the documentation as well as use meaningful identifiers (`teaser`, `teaser-include`, `teaser-service`...).

# Changelog

- 📖 Update documentation regarding Document Teasers
- 📖 Update `opener` useage for WSL 2 (Windows) in README.md

2024-04-29 10:23 UTC, benib reviewed
I have left some comments. I know that the example wasn't so clear before and you already improved it. While at it, you might want to consider my input.

2024-04-29 10:23 UTC, benib commented on content/guides/documents/includes/document-teasers.md
> +            component: 'my-teaser',
With some newer projects, we started naming this component `teaser-template` to distinguish it from the `article-teaser` aka. `teaser-include`.

2024-04-29 10:23 UTC, benib commented on content/guides/documents/includes/document-teasers.md
> +              showByline: 'byline from include',
In real world, those would come from the `documentVersion.metadata` as well, do you want to adjust this?

2024-04-29 10:23 UTC, benib commented on content/guides/documents/includes/document-teasers.md
> +              link: 'https://example.com'
I suggest to omit this one. It's confusing if the `teaser-template` contains a `doc-link` directive. If it has one, a user sees a UI to change this link, but she shouldn't. Adding a link to the teaser is normally done in the delivery rendering.

2024-04-29 10:23 UTC, benib commented on content/guides/documents/includes/document-teasers.md
> +  name: 'my-teaser',
name it `teaser-template` if you change it above.

2024-04-29 10:23 UTC, benib commented on content/guides/documents/includes/document-teasers.md
> +    <a class="teaser" doc-link="link" style="display: block;">
remove the `a` with the `doc-link` directive and change it to a `div` if you agree that it's a bit weird.

2024-04-29 10:23 UTC, benib commented on content/guides/documents/includes/document-teasers.md
> +  }],
Although this is nice as an example of how to use `toggle` directives, I have never seen this done like that in real world. Instead, different `teaser-template`-components would be used. So I suggest to omit this and make the example simpler with that.

2024-04-29 10:23 UTC, benib commented on content/guides/documents/includes/document-teasers.md
> +      name: 'teaser-include-dir-id',
I'm slightly confused by the name `*-dir-id`. Is this an abbreviation for something?

2024-04-29 10:32 UTC, christian-schmitz-ld commented on content/guides/documents/includes/document-teasers.md
> +            component: 'my-teaser',
Sure, I think import is only that they are unique within the guide. So you mean for `my-teaser` you started using `teaser-template`?

2024-04-29 10:36 UTC, benib commented on content/guides/documents/includes/document-teasers.md
> +            component: 'my-teaser',
Yes, this would be in line with what I have seen in recent new project configurations like `F.A.Z.`. I'm not up to date with the definitions and best practices you have in your team though, but it definitely makes sense to reflect them in the documentation.

2024-04-29 10:53 UTC, christian-schmitz-ld commented on content/guides/documents/includes/document-teasers.md
> +    <a class="teaser" doc-link="link" style="display: block;">
Sure I will, there are side functionalities which I still don't understand in detail yet (like the doc-include). I used the upstream implementation from the service project (there is the teaser in use) and took it from there thinking this makes sense. Maybe we should also change the implementation on the upstream demo projects to keep everything aligned.

2024-04-29 10:56 UTC, christian-schmitz-ld commented on content/guides/documents/includes/document-teasers.md
> +      name: 'teaser-include-dir-id',
This I explicitly changed because it was very confusing having one more `teaser` identifier. As  I tested it I saw there is no impact in changing this id. Since it is a directive I just used *-dir-id. If it has an impact on the implementation then I really would like to understand.

2024-04-29 15:19 UTC, benib commented on content/guides/documents/includes/document-teasers.md
> +      name: 'teaser-include-dir-id',
This will influence the data-model for the document. This is how the `content` of the document will look like:
```
content: [{
  component: 'teaser-include',
  content: {
    'teaser-include-dir-id': { <-- the name of the directive
       params: {
          // the params defined by the paramsSchema of the service
       },
       service: 'teaser-service'
    }
  }
}[
```

There is some impact on the implementation as it is defining the data model of the resulting document.

2024-04-29 15:23 UTC, benib requested changes

2024-04-30 14:54 UTC, benib approved these changes
👏 

I would suggest to remove the `readOnly` functionality from the example here. This is really just there in the upstream service example project to test some behavior without having to change the code.

Otherwise this looks very nice and clean, thank you 👍

2024-04-30 16:11 UTC, merged

2024-04-30 16:12 UTC, livingdocs-automation commented
:tada: This PR is included in version 1.93.8 :tada:

The release is available on [GitHub release](https://github.com/livingdocsIO/documentation/releases/tag/v1.93.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: